<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Local;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'title' => 'Restaurante Sabor Mineiro',
                'description' => 'Um restaurante típico mineiro com comida caseira.',
                'images' => ['imagem 1.jpeg'],
                'cep' => '30140071',
                'address' => 'Av. Afonso Pena',
                'address_number' => '1234',
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'phone' => '(31) 3333-4444',
                'contact_email' => 'contato@sabormineiro.com',
                'category' => 'Restaurante',
                'features' => ['wifi','estacionamento','acessivel','ar_condicionado'],
                'working_hours' => ['segunda-sexta' => ['opening' => '11:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Pizzaria Napoli',
                'description' => 'Pizzas artesanais assadas no forno a lenha.',
                'images' => ['imagem 2.jpeg'],
                'cep' => '04002030',
                'address' => 'Rua Vergueiro',
                'address_number' => '890',
                'neighborhood' => 'Vila Mariana',
                'city' => 'São Paulo',
                'state' => 'SP',
                'phone' => '(11) 2222-5555',
                'contact_email' => 'contato@napoli.com',
                'category' => 'Pizzaria',
                'features' => ['delivery','wifi','ar_condicionado'],
                'working_hours' => ['todos-dias' => ['opening' => '18:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Cafeteria Aroma',
                'description' => 'Cafés especiais e sobremesas deliciosas.',
                'images' => ['imagem 3.jpeg'],
                'cep' => '20040002',
                'address' => 'Rua do Ouvidor',
                'address_number' => '456',
                'neighborhood' => 'Centro',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'phone' => '(21) 9888-7777',
                'contact_email' => 'atendimento@aromacafe.com',
                'category' => 'Cafeteria',
                'features' => ['wifi','pet_friendly','ar_condicionado'],
                'working_hours' => ['segunda-sabado' => ['opening' => '08:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Churrascaria Boi na Brasa',
                'description' => 'Rodízio de carnes nobres com buffet variado.',
                'images' => ['imagem 4.jpg'],
                'cep' => '60060230',
                'address' => 'Av. Beira Mar',
                'address_number' => '2300',
                'neighborhood' => 'Meireles',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'phone' => '(85) 3344-1212',
                'contact_email' => 'reservas@boinabrasa.com',
                'category' => 'Churrascaria',
                'features' => ['estacionamento','ar_condicionado','delivery'],
                'working_hours' => ['todos-dias' => ['opening' => '11:30', 'closing' => '23:00']],
            ],
            [
                'title' => 'Padaria Doce Pão',
                'description' => 'Pães artesanais, doces e salgados fresquinhos.',
                'images' => ['imagem 5.jpg'],
                'cep' => '88015000',
                'address' => 'Rua Felipe Schmidt',
                'address_number' => '777',
                'neighborhood' => 'Centro',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'phone' => '(48) 3222-9999',
                'contact_email' => 'contato@docepao.com',
                'category' => 'Padaria',
                'features' => ['wifi','delivery','pet_friendly'],
                'working_hours' => ['segunda-domingo' => ['opening' => '06:00', 'closing' => '21:00']],
            ],
            [
                'title' => 'Hamburgueria Burger Club',
                'description' => 'Hambúrgueres artesanais com carnes selecionadas.',
                'images' => ['imagem 6.jpg'],
                'cep' => '74000000',
                'address' => 'Av. Goiás',
                'address_number' => '320',
                'neighborhood' => 'Setor Central',
                'city' => 'Goiânia',
                'state' => 'GO',
                'phone' => '(62) 3333-2222',
                'contact_email' => 'fale@burgerclub.com',
                'category' => 'Hamburgueria',
                'features' => ['delivery','wifi','ar_condicionado'],
                'working_hours' => ['todos-dias' => ['opening' => '17:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Sorveteria Gelato Brasil',
                'description' => 'Sorvetes italianos feitos com frutas frescas.',
                'images' => ['imagem 7.jpg'],
                'cep' => '69005010',
                'address' => 'Av. Eduardo Ribeiro',
                'address_number' => '50',
                'neighborhood' => 'Centro',
                'city' => 'Manaus',
                'state' => 'AM',
                'phone' => '(92) 4444-5656',
                'contact_email' => 'gelato@brasil.com',
                'category' => 'Sorveteria',
                'features' => ['wifi','pet_friendly'],
                'working_hours' => ['todos-dias' => ['opening' => '12:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Bar do Porto',
                'description' => 'Drinks exclusivos e música ao vivo.',
                'images' => ['imagem 8.jpg'],
                'cep' => '40020000',
                'address' => 'Av. Contorno',
                'address_number' => '99',
                'neighborhood' => 'Comércio',
                'city' => 'Salvador',
                'state' => 'BA',
                'phone' => '(71) 3456-1111',
                'contact_email' => 'contato@bardoporto.com',
                'category' => 'Bar',
                'features' => ['musica_ao_vivo','wifi','estacionamento'],
                'working_hours' => ['quarta-domingo' => ['opening' => '18:00', 'closing' => '02:00']],
            ],
            [
                'title' => 'Hotel Vista Mar',
                'description' => 'Hotel de frente para o mar com suítes modernas.',
                'images' => ['imagem 9.jpg'],
                'cep' => '66010000',
                'address' => 'Av. Presidente Vargas',
                'address_number' => '3456',
                'neighborhood' => 'Campina',
                'city' => 'Belém',
                'state' => 'PA',
                'phone' => '(91) 9988-3344',
                'contact_email' => 'reservas@vistamar.com',
                'category' => 'Hotel',
                'features' => ['wifi','piscina','estacionamento','ar_condicionado'],
                'working_hours' => ['todos-dias' => ['opening' => '00:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Hostel Juventude',
                'description' => 'Acomodações econômicas e ambiente descontraído.',
                'images' => ['imagem 10.jpg'],
                'cep' => '89010025',
                'address' => 'Rua XV de Novembro',
                'address_number' => '210',
                'neighborhood' => 'Centro',
                'city' => 'Blumenau',
                'state' => 'SC',
                'phone' => '(47) 3223-2323',
                'contact_email' => 'info@hosteljuventude.com',
                'category' => 'Hostel',
                'features' => ['wifi','pet_friendly','cafe_da_manha'],
                'working_hours' => ['todos-dias' => ['opening' => '00:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Parque Verde Vida',
                'description' => 'Área verde para piqueniques, trilhas e esportes.',
                'images' => ['imagem 11.jpg'],
                'cep' => '97015200',
                'address' => 'Av. Rio Branco',
                'address_number' => '1500',
                'neighborhood' => 'Centro',
                'city' => 'Santa Maria',
                'state' => 'RS',
                'phone' => '(55) 3333-9999',
                'contact_email' => 'contato@verdevida.com',
                'category' => 'Parque',
                'features' => ['estacionamento','pet_friendly','area_criancas'],
                'working_hours' => ['todos-dias' => ['opening' => '07:00', 'closing' => '19:00']],
            ],
            [
                'title' => 'Academia PowerFit',
                'description' => 'Academia moderna com equipamentos de última geração.',
                'images' => ['imagem 12.jpg'],
                'cep' => '69020100',
                'address' => 'Av. Constantino Nery',
                'address_number' => '1122',
                'neighborhood' => 'Chapada',
                'city' => 'Manaus',
                'state' => 'AM',
                'phone' => '(92) 2233-4455',
                'contact_email' => 'powerfit@academia.com',
                'category' => 'Academia',
                'features' => ['wifi','estacionamento','ar_condicionado'],
                'working_hours' => ['segunda-sabado' => ['opening' => '06:00', 'closing' => '22:00']],
            ],
        ];

        foreach ($locations as $loc) {
            Local::create([
                'title' => $loc['title'],
                'description' => $loc['description'],
                'images' => $loc['images'],
                'cep' => $loc['cep'],
                'address' => $loc['address'],
                'address_number' => $loc['address_number'],
                'neighborhood' => $loc['neighborhood'],
                'city' => $loc['city'],
                'state' => $loc['state'],
                'phone' => $loc['phone'],
                'contact_email' => $loc['contact_email'],
                'category' => $loc['category'],
                'features' => $loc['features'],
                'working_hours' => $loc['working_hours'],
                'user_name' => 'Admin',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}