<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Local;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'title' => 'Restaurante Sabor Mineiro',
                'description' => 'Um restaurante típico mineiro com comida caseira.',
                'images' => ['Imagem 1.jpeg'],
                'cep' => '30140071',
                'address' => 'Av. Afonso Pena',
                'address_number' => '1234',
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'phone' => '(31) 3333-4444',
                'contact_email' => 'contato@sabormineiro.com',
                'category' => 'restaurante',
                'features' => ['wifi','estacionamento','acessivel','ar_condicionado'],
                'working_hours' => ['segunda-sexta' => ['opening' => '11:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Pizzaria Napoli',
                'description' => 'Pizzas artesanais assadas no forno a lenha.',
                'images' => ['Imagem 2.jpeg'],
                'cep' => '04002030',
                'address' => 'Rua Vergueiro',
                'address_number' => '890',
                'neighborhood' => 'Vila Mariana',
                'city' => 'São Paulo',
                'state' => 'SP',
                'phone' => '(11) 2222-5555',
                'contact_email' => 'contato@napoli.com',
                'category' => 'pizzaria',
                'features' => ['delivery','wifi','ar_condicionado'],
                'working_hours' => ['todos-dias' => ['opening' => '18:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Cafeteria Aroma',
                'description' => 'Cafés especiais e sobremesas deliciosas.',
                'images' => ['Imagem 3.jpeg'],
                'cep' => '20040002',
                'address' => 'Rua do Ouvidor',
                'address_number' => '456',
                'neighborhood' => 'Centro',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'phone' => '(21) 9888-7777',
                'contact_email' => 'atendimento@aromacafe.com',
                'category' => 'cafe',
                'features' => ['wifi','pet_friendly','ar_condicionado','cafe_manha'],
                'working_hours' => ['segunda-sabado' => ['opening' => '08:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Churrascaria Boi na Brasa',
                'description' => 'Rodízio de carnes nobres com buffet variado.',
                'images' => ['Imagem 4.jpg'],
                'cep' => '60060230',
                'address' => 'Av. Beira Mar',
                'address_number' => '2300',
                'neighborhood' => 'Meireles',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'phone' => '(85) 3344-1212',
                'contact_email' => 'reservas@boinabrasa.com',
                'category' => 'restaurante',
                'features' => ['estacionamento','ar_condicionado','delivery','bebidas'],
                'working_hours' => ['todos-dias' => ['opening' => '11:30', 'closing' => '23:00']],
            ],
            [
                'title' => 'Padaria Doce Pão',
                'description' => 'Pães artesanais, doces e salgados fresquinhos.',
                'images' => ['Imagem 5.jpg'],
                'cep' => '88015000',
                'address' => 'Rua Felipe Schmidt',
                'address_number' => '777',
                'neighborhood' => 'Centro',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'phone' => '(48) 3222-9999',
                'contact_email' => 'contato@docepao.com',
                'category' => 'padaria',
                'features' => ['wifi','delivery','pet_friendly','cafe_manha'],
                'working_hours' => ['segunda-domingo' => ['opening' => '06:00', 'closing' => '21:00']],
            ],
            [
                'title' => 'Hamburgueria Burger Club',
                'description' => 'Hambúrgueres artesanais com carnes selecionadas.',
                'images' => ['Imagem 6.jpg'],
                'cep' => '74000000',
                'address' => 'Av. Goiás',
                'address_number' => '320',
                'neighborhood' => 'Setor Central',
                'city' => 'Goiânia',
                'state' => 'GO',
                'phone' => '(62) 3333-2222',
                'contact_email' => 'fale@burgerclub.com',
                'category' => 'hamburgueria',
                'features' => ['delivery','wifi','ar_condicionado','bebidas'],
                'working_hours' => ['todos-dias' => ['opening' => '17:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Sorveteria Gelato Brasil',
                'description' => 'Sorvetes italianos feitos com frutas frescas.',
                'images' => ['Imagem 7.jpg'],
                'cep' => '69005010',
                'address' => 'Av. Eduardo Ribeiro',
                'address_number' => '50',
                'neighborhood' => 'Centro',
                'city' => 'Manaus',
                'state' => 'AM',
                'phone' => '(92) 4444-5656',
                'contact_email' => 'gelato@brasil.com',
                'category' => 'sorveteria',
                'features' => ['wifi','pet_friendly'],
                'working_hours' => ['todos-dias' => ['opening' => '12:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Bar do Porto',
                'description' => 'Drinks exclusivos e música ao vivo.',
                'images' => ['Imagem 8.jpg'],
                'cep' => '40020000',
                'address' => 'Av. Contorno',
                'address_number' => '99',
                'neighborhood' => 'Comércio',
                'city' => 'Salvador',
                'state' => 'BA',
                'phone' => '(71) 3456-1111',
                'contact_email' => 'contato@bardoporto.com',
                'category' => 'bar',
                'features' => ['musica_ao_vivo','wifi','estacionamento','bebidas'],
                'working_hours' => ['quarta-domingo' => ['opening' => '18:00', 'closing' => '02:00']],
            ],
            [
                'title' => 'Hotel Vista Mar',
                'description' => 'Hotel de frente para o mar com suítes modernas.',
                'images' => ['Imagem 9.jpg'],
                'cep' => '66010000',
                'address' => 'Av. Presidente Vargas',
                'address_number' => '3456',
                'neighborhood' => 'Campina',
                'city' => 'Belém',
                'state' => 'PA',
                'phone' => '(91) 9988-3344',
                'contact_email' => 'reservas@vistamar.com',
                'category' => 'hotel',
                'features' => ['wifi','piscina','estacionamento','ar_condicionado'],
                'working_hours' => ['todos-dias' => ['opening' => '00:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Hostel Juventude',
                'description' => 'Acomodações econômicas e ambiente descontraído.',
                'images' => ['Imagem 10.jpg'],
                'cep' => '89010025',
                'address' => 'Rua XV de Novembro',
                'address_number' => '210',
                'neighborhood' => 'Centro',
                'city' => 'Blumenau',
                'state' => 'SC',
                'phone' => '(47) 3223-2323',
                'contact_email' => 'info@hosteljuventude.com',
                'category' => 'pousada',
                'features' => ['wifi','pet_friendly','cafe_manha'],
                'working_hours' => ['todos-dias' => ['opening' => '00:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Parque Verde Vida',
                'description' => 'Área verde para piqueniques, trilhas e esportes.',
                'images' => ['Imagem 11.jpg'],
                'cep' => '97015200',
                'address' => 'Av. Rio Branco',
                'address_number' => '1500',
                'neighborhood' => 'Centro',
                'city' => 'Santa Maria',
                'state' => 'RS',
                'phone' => '(55) 3333-9999',
                'contact_email' => 'contato@verdevida.com',
                'category' => 'parque',
                'features' => ['estacionamento','pet_friendly','playground','jardim'],
                'working_hours' => ['todos-dias' => ['opening' => '07:00', 'closing' => '19:00']],
            ],
            [
                'title' => 'Academia PowerFit',
                'description' => 'Academia moderna com equipamentos de última geração.',
                'images' => ['Imagem 12.jpg'],
                'cep' => '69020100',
                'address' => 'Av. Constantino Nery',
                'address_number' => '1122',
                'neighborhood' => 'Chapada',
                'city' => 'Manaus',
                'state' => 'AM',
                'phone' => '(92) 2233-4455',
                'contact_email' => 'powerfit@academia.com',
                'category' => 'academia',
                'features' => ['wifi','estacionamento','ar_condicionado','banheiro'],
                'working_hours' => ['segunda-sabado' => ['opening' => '06:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Loja Mundo Tech',
                'description' => 'Loja com os últimos gadgets e acessórios.',
                'images' => ['Imagem 13.jpg'],
                'cep' => '01001000',
                'address' => 'Rua das Flores',
                'address_number' => '100',
                'neighborhood' => 'Centro',
                'city' => 'São Paulo',
                'state' => 'SP',
                'phone' => '(11) 4000-1000',
                'contact_email' => 'contato@mundotech.com',
                'category' => 'loja',
                'features' => ['estacionamento','tomadas','acessivel'],
                'working_hours' => ['segunda-sabado' => ['opening' => '09:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Museu da Cidade',
                'description' => 'Acervo histórico com exposições permanentes e temporárias.',
                'images' => ['Imagem 14.jpg'],
                'cep' => '70040000',
                'address' => 'Praça das Artes',
                'address_number' => '1',
                'neighborhood' => 'Centro',
                'city' => 'Brasília',
                'state' => 'DF',
                'phone' => '(61) 3222-4444',
                'contact_email' => 'info@museudacidade.com',
                'category' => 'museu',
                'features' => ['acessivel','banheiro','estacionamento','jardim'],
                'working_hours' => ['terça-domingo' => ['opening' => '10:00', 'closing' => '18:00']],
            ],
            [
                'title' => 'Cine Lumière',
                'description' => 'Cinema independente com programação variada.',
                'images' => ['Imagem 15.jpg'],
                'cep' => '40020030',
                'address' => 'Rua do Cinema',
                'address_number' => '75',
                'neighborhood' => 'Jardins',
                'city' => 'Salvador',
                'state' => 'BA',
                'phone' => '(71) 3333-7777',
                'contact_email' => 'bilheteria@cinelumiere.com',
                'category' => 'cinema',
                'features' => ['ar_condicionado','tv','banheiro'],
                'working_hours' => ['todos-dias' => ['opening' => '13:00', 'closing' => '23:00']],
            ],
            [
                'title' => 'Teatro Municipal',
                'description' => 'Espaço para apresentações de dança, música e teatro.',
                'images' => ['Imagem 16.jpg'],
                'cep' => '30120010',
                'address' => 'Praça do Teatro',
                'address_number' => '10',
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'phone' => '(31) 3222-1000',
                'contact_email' => 'contato@teatromunicipal.com',
                'category' => 'teatro',
                'features' => ['acessivel','musica_ao_vivo','banheiro'],
                'working_hours' => ['segunda-domingo' => ['opening' => '09:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Praia do Sol',
                'description' => 'Praia com faixa de areia ampla e quiosques.',
                'images' => ['Imagem 17.jpg'],
                'cep' => '49000000',
                'address' => 'Av. Beira Mar',
                'address_number' => 's/n',
                'neighborhood' => 'Orla',
                'city' => 'Aracaju',
                'state' => 'SE',
                'phone' => '(79) 9999-0000',
                'contact_email' => 'info@praiadosol.com',
                'category' => 'praia',
                'features' => ['estacionamento','cais_embarcacoes','vista_panoramica','pet_friendly'],
                'working_hours' => ['todos-dias' => ['opening' => '00:00', 'closing' => '23:59']],
            ],
            [
                'title' => 'Zoológico Central',
                'description' => 'Grande zoológico com áreas temáticas e aquário.',
                'images' => ['Imagem 18.jpg'],
                'cep' => '60000000',
                'address' => 'Av. dos Animais',
                'address_number' => '500',
                'neighborhood' => 'Zona Leste',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'phone' => '(85) 4000-5000',
                'contact_email' => 'contato@zoologico.com',
                'category' => 'zoo_aquario',
                'features' => ['jardim','playground','estacionamento','acessivel'],
                'working_hours' => ['todos-dias' => ['opening' => '08:00', 'closing' => '17:00']],
            ],
            [
                'title' => 'Biblioteca Municipal',
                'description' => 'Acervo com livros, salas de estudo e eventos culturais.',
                'images' => ['Imagem 19.jpg'],
                'cep' => '70040900',
                'address' => 'Rua da Leitura',
                'address_number' => '120',
                'neighborhood' => 'Centro',
                'city' => 'Brasília',
                'state' => 'DF',
                'phone' => '(61) 3333-1212',
                'contact_email' => 'biblioteca@municipal.com',
                'category' => 'biblioteca',
                'features' => ['acessivel','tomadas','wifi'],
                'working_hours' => ['segunda-sexta' => ['opening' => '08:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Centro Histórico Antigo',
                'description' => 'Região histórica com monumentos e lojas tradicionais.',
                'images' => ['Imagem 20.jpg'],
                'cep' => '40000010',
                'address' => 'Rua do Antigo',
                'address_number' => 's/n',
                'neighborhood' => 'Centro',
                'city' => 'Salvador',
                'state' => 'BA',
                'phone' => '(71) 4000-0000',
                'contact_email' => 'info@centrohistorico.com',
                'category' => 'centro_historico',
                'features' => ['ponto_turistico','vista_panoramica','guia_turistico' /* note: guia_turistico is custom - if your app validates features strictly, substitute */],
                'working_hours' => ['todos-dias' => ['opening' => '08:00', 'closing' => '18:00']],
            ],
            [
                'title' => 'Mirante das Estrelas',
                'description' => 'Mirante com vista panorâmica da cidade ao pôr do sol.',
                'images' => ['Imagem 21.jpg'],
                'cep' => '80000000',
                'address' => 'Estr. do Mirante',
                'address_number' => '1000',
                'neighborhood' => 'Alto',
                'city' => 'Curitiba',
                'state' => 'PR',
                'phone' => '(41) 3333-7777',
                'contact_email' => 'mirante@estrelas.com',
                'category' => 'mirante',
                'features' => ['vista_panoramica','terraco','banheiro'],
                'working_hours' => ['todos-dias' => ['opening' => '06:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Trilha Vale Verde',
                'description' => 'Trilha de nível leve com cachoeira no final.',
                'images' => ['Imagem 22.jpg'],
                'cep' => '69030000',
                'address' => 'Estrada da Serra',
                'address_number' => 's/n',
                'neighborhood' => 'Zona Rural',
                'city' => 'Manaus',
                'state' => 'AM',
                'phone' => '(92) 3344-2244',
                'contact_email' => 'trilha@valeverde.com',
                'category' => 'trilha',
                'features' => ['jardim','vista_panoramica','acessivel'],
                'working_hours' => ['todos-dias' => ['opening' => '07:00', 'closing' => '17:00']],
            ],
            [
                'title' => 'Jardim Botânico Nacional',
                'description' => 'Grande área com espécies nativas e trilhas educativas.',
                'images' => ['Imagem 23.jpg'],
                'cep' => '70070000',
                'address' => 'Av. das Palmeiras',
                'address_number' => '750',
                'neighborhood' => 'Zona Sul',
                'city' => 'Brasília',
                'state' => 'DF',
                'phone' => '(61) 3222-8888',
                'contact_email' => 'info@jardimbotanico.com',
                'category' => 'jardim_botanico',
                'features' => ['jardim','playground','acessivel','estacionamento'],
                'working_hours' => ['todos-dias' => ['opening' => '08:00', 'closing' => '18:00']],
            ],
            [
                'title' => 'Loja Artes & Cia',
                'description' => 'Produtos de artesanato local e lembranças.',
                'images' => ['Imagem 24.jpg'],
                'cep' => '88010000',
                'address' => 'Rua do Artesão',
                'address_number' => '45',
                'neighborhood' => 'Centro',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'phone' => '(48) 3222-4545',
                'contact_email' => 'contato@artescia.com',
                'category' => 'loja_artesanato',
                'features' => ['acessivel','estacionamento','tomadas'],
                'working_hours' => ['segunda-sabado' => ['opening' => '09:00', 'closing' => '18:00']],
            ],
            [
                'title' => 'Ponto Turístico Miragaia',
                'description' => 'Local turístico famoso pela arquitetura e eventos culturais.',
                'images' => ['Imagem 25.jpg'],
                'cep' => '50000000',
                'address' => 'Largo do Miragaia',
                'address_number' => 's/n',
                'neighborhood' => 'Centro',
                'city' => 'Recife',
                'state' => 'PE',
                'phone' => '(81) 3222-2222',
                'contact_email' => 'turismo@miragaia.com',
                'category' => 'ponto_turistico',
                'features' => ['vista_panoramica','estacionamento','banheiro','acessivel'],
                'working_hours' => ['todos-dias' => ['opening' => '08:00', 'closing' => '20:00']],
            ],
            [
                'title' => 'Cervejaria Artesanal Capixaba',
                'description' => 'Cervejas artesanais produzidas localmente com variedade de estilos.',
                'images' => ['Imagem 1.jpeg'],
                'cep' => '29010000',
                'address' => 'Rua do Lúpulo',
                'address_number' => '200',
                'neighborhood' => 'Praia do Canto',
                'city' => 'Vitória',
                'state' => 'ES',
                'phone' => '(27) 3333-1010',
                'contact_email' => 'contato@cervejariacapixaba.com',
                'category' => 'cervejaria',
                'features' => ['delivery','wifi','bar','pet_friendly'],
                'working_hours' => ['quarta-domingo' => ['opening' => '16:00', 'closing' => '23:00']],
            ],
            [
                'title' => 'Bistrô Le Jardin',
                'description' => 'Bistrô francês com pratos sofisticados e ambiente aconchegante.',
                'images' => ['Imagem 2.jpeg'],
                'cep' => '80010100',
                'address' => 'Rua das Flores',
                'address_number' => '88',
                'neighborhood' => 'Batel',
                'city' => 'Curitiba',
                'state' => 'PR',
                'phone' => '(41) 3222-8888',
                'contact_email' => 'reservas@lejardin.com',
                'category' => 'restaurante',
                'features' => ['wifi','estacionamento','ar_condicionado','musica_ao_vivo'],
                'working_hours' => ['terça-domingo' => ['opening' => '12:00', 'closing' => '22:00']],
            ],
            [
                'title' => 'Espaço Cultural Solar',
                'description' => 'Galeria de arte, exposições e workshops culturais para todas as idades.',
                'images' => ['Imagem 3.jpeg'],
                'cep' => '40010100',
                'address' => 'Praça Central',
                'address_number' => '55',
                'neighborhood' => 'Centro',
                'city' => 'Salvador',
                'state' => 'BA',
                'phone' => '(71) 4000-2000',
                'contact_email' => 'info@solarcultural.com',
                'category' => 'cultural',
                'features' => ['acessivel','banheiro','jardim','wifi'],
                'working_hours' => ['segunda-sábado' => ['opening' => '09:00', 'closing' => '19:00']],
            ],
            [
                'title' => 'Parque Aquático Splash',
                'description' => 'Diversão para toda a família com piscinas, toboáguas e área infantil.',
                'images' => ['Imagem 4.jpg'],
                'cep' => '22041000',
                'address' => 'Av. das Ondas',
                'address_number' => '500',
                'neighborhood' => 'Zona Leste',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'phone' => '(21) 4002-3000',
                'contact_email' => 'contato@splash.com',
                'category' => 'parque',
                'features' => ['estacionamento','playground','piscina','acessivel'],
                'working_hours' => ['todos-dias' => ['opening' => '08:00', 'closing' => '18:00']],
            ],
            [
                'title' => 'Café Literário Letras & Sabores',
                'description' => 'Café com ambiente literário, livros para leitura e doces artesanais.',
                'images' => ['Imagem 5.jpg'],
                'cep' => '30120020',
                'address' => 'Rua dos Poetas',
                'address_number' => '34',
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'phone' => '(31) 3333-5678',
                'contact_email' => 'contato@letrasesabores.com',
                'category' => 'cafe',
                'features' => ['wifi','pet_friendly','ar_condicionado','cafe_manha'],
                'working_hours' => ['segunda-domingo' => ['opening' => '07:00', 'closing' => '21:00']],
            ],
        ];

        foreach ($locations as $loc) {
            Local::create([
                'title' => $loc['title'],
                'description' => $loc['description'],
                'images' => $loc['images'],
                'cep' => $loc['cep'],
                'address' => $loc['address'],
                'address_number' => $loc['address_number'],
                'neighborhood' => $loc['neighborhood'],
                'city' => $loc['city'],
                'state' => $loc['state'],
                'phone' => $loc['phone'],
                'contact_email' => $loc['contact_email'],
                'category' => $loc['category'],
                'features' => $loc['features'],
                'working_hours' => $loc['working_hours'],
                'user_name' => 'Admin',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}